# Generated by Django 5.1.2 on 2024-10-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoMVC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='completed',
        ),
    ]
